projectName = Vendor Invoice Management Project
environment = qa

# Environment configuration
api.base.url=https://tgifcappdev.azurewebsites.net/backend/
api.version=v1

# Performance settings
performance.threads=50
performance.ramp.up.seconds=30
performance.hold.duration.minutes=5
performance.threshold.response.time.ms=500

#UI settings
ui.url=http://20.198.242.204/
ui.browser=edge