package ai.metayb.api.publicmaintenancecron.publicworkflow;

import io.qameta.allure.Description;
import io.qameta.allure.Epic;
import io.qameta.allure.Feature;
import io.qameta.allure.Story;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.Test;
import testUtils.BaseApiTest;

import static io.restassured.RestAssured.given;

/**
 * "07. Public, Maintenance &amp; Cron / Public Workflow" - the single Postman
 * request, "Verify Email Link". Genuinely public (verified live: works with no
 * Authorization header at all).
 *
 * No real, currently-valid email verification token is known to exist for this
 * tenant (they are single-use and generated by a real email-verification flow that
 * is out of scope here), so the "token accepted" positive path is not automated -
 * test data unavailable. Postman's own saved request body is "{}" (no token field
 * at all), so the validation error it produces is documented per Step 8 rather
 * than inventing a token.
 */
@Epic("BrandRunners Web API")
@Feature("Public, Maintenance & Cron - Public Workflow")
public class VerifyEmailLinkApiTest extends BaseApiTest {

    @Test(groups = {"api", "regression"}, description = "Verify Email Link, called exactly as Postman defines it (empty body), returns a validation error")
    @Story("Verify Email Link")
    @Description("Verified live: HTTP 400, message 'Verification token is required', with no Authorization header at all - confirms this endpoint is genuinely public.")
    public void verifyEmailLinkWithEmptyBodyReturnsValidationError() {
        Response response = given().spec(noAuthRequestSpecification)
                .contentType("application/json")
                .body("{}")
                .post("/web/public/workflow/verify-email-link");

        Assert.assertEquals(response.statusCode(), 400);
        Assert.assertEquals(response.jsonPath().getString("message"), "Verification token is required");
    }

    @Test(groups = {"api", "regression", "negative"}, description = "Verify Email Link with an unknown/invalid token fails")
    @Story("Verify Email Link")
    @Description("Verified live: HTTP 400, message 'Invalid or expired verification link' - distinct from the missing-token message, proving the token IS actually validated server-side rather than merely checked for presence.")
    public void verifyEmailLinkWithInvalidTokenFails() {
        Response response = given().spec(noAuthRequestSpecification)
                .contentType("application/json")
                .body("{\"token\":\"invalid-placeholder-token-xyz\"}")
                .post("/web/public/workflow/verify-email-link");

        Assert.assertEquals(response.statusCode(), 400);
        Assert.assertEquals(response.jsonPath().getString("message"), "Invalid or expired verification link");
    }
}
